<?php
//////////////Begin Configurations///////////
$server = "";                            //Server you want to check
$GLOBALS['character'] = "";       //If you want to check your Crafted Signature
$keyid = "";                 //Get your own API Key ID at https://xivapi.com/
////////////Tank gear////////////
$TankLeft_id = 23783;     //Starting ID for tank shield via XIVDB item#
$TankRight_id = 23826;    //Starting ID for tank ear via XIVDB item#

////////////Heal Gear////////////
$HealLeft_id = 23814;     //Starting ID for healer head via XIVDB item#
$HealRight_id = 23829;    //Starting ID for healer ear via XIVDB item#

////////////Cast Gear////////////
$CastLeft_id = 23820;    //Starting ID for casting header via XIVDB item#
$CastRight_id = 23830;   //Starting ID for casting ear via XIVDB item#

////////////Aim Gear////////////
$AimLeft_id = 23802;    //Starting ID for aiming head via XIVDB item#
$AimRight_id = 23828;   //Starting ID for aiming ear via XIVDB item#

////////////Scout Gear////////////
$ScoutLeft_id = 23808;    //Starting ID for scouting ear via XIVDB item#

////////////Maim Gear////////////
$MaimLeft_id = 23790;    //Starting ID for maiming head via XIVDB item#
$MaimRight_id = 23827;   //Starting ID for maiming ear via XIVDB item#

////////////Strike Gear////////////
$StirkeLeft_id = 23796;   //Starting ID for striking head via XIVDB item#

////////////Weapons////////////
$Weapon_id = 23768;      //Starting ID for PLD wepaon via XIVDB item# PLD wepaon

////////////Crafting Gear////////////
$CraftLeft_id = 22905;      //Starting ID for Craft head via XIVDB item# PLD wepaon
$CraftRight_id = 22916;      //Starting ID for Craft Ear via XIVDB item# PLD wepaon

////////////Gathering Gear////////////
$GathLeft_id = 22910;      //Starting ID for Gath Head via XIVDB item# PLD wepaon
$GathRight_id = 22921;      //Starting ID for Gath Ear via XIVDB item# PLD wepaon

////////////Craft Weapons////////////
$CraftWeaponMH_id = 22884;      //Starting ID for CRP MH via XIVDB item# PLD wepaon
$CraftWeaponOH_id = 22895;      //Starting ID for CRP OH via XIVDB item# PLD wepaon

////////////Gath Weapons////////////
$GathWeaponMH_id = 22892;      //Starting ID for MIN MH via XIVDB item# PLD wepaon
$GathWeaponOH_id = 22903;      //Starting ID for MIN OH wepaon via XIVDB item# PLD wepaon
/////////////End Configurations//////////////


?>
